apiVersion: v1
kind: Namespace
metadata:
  name: scopeapi
  labels:
    name: scopeapi
    environment: production
    app: scopeapi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: scopeapi-quota
  namespace: scopeapi
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    persistentvolumeclaims: "10"
    services: "20"
    pods: "20"
